version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    versioning-strategy: increase-if-necessary
    allow:
      - dependency-type: direct
    schedule:
      interval: monthly
    open-pull-requests-limit: 20
    reviewers:
      - "RSickenberg"
  - package-ecosystem: npm
    directory: "/"
    versioning-strategy: increase-if-necessary
    allow:
      - dependency-type: direct
    schedule:
      interval: monthly
    open-pull-requests-limit: 20
    reviewers:
      - "RSickenberg"
